name: PR Preview (Cloudflare Pages)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site (Astro)
        run: npm run build

      - name: Deploy preview to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Create or use an existing Pages project name.
          # To avoid interfering with production, this defaults to a preview-specific project.
          projectName: knots-official-site-preview
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Ensure a unique preview per PR
          branch: pr-${{ github.event.number }}

