name: PR Preview (Cloudflare Workers)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site (Astro)
        run: npm run build

      - name: Install Wrangler CLI
        run: npm i -g wrangler@4

      - name: Deploy preview to Cloudflare Workers
        id: deploy
        run: |
          NAME="knots-pr-${{ github.event.pull_request.number }}"
          echo "worker_name=$NAME" >> $GITHUB_OUTPUT
          # Deploy static assets from dist using wrangler.jsonc
          wrangler deploy --name "$NAME" --config wrangler.jsonc --assets dist | tee deploy.log
          URL=$(grep -Eo 'https://[^ ]+workers\.dev' deploy.log | head -n1 || true)
          if [ -n "$URL" ]; then
            echo "url=$URL" >> $GITHUB_OUTPUT
            echo "Preview URL: $URL"
          else
            echo "Preview URL not found in output" >&2
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment preview URL on PR
        if: ${{ github.event.action != 'closed' && steps.deploy.outputs.url != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = core.getInput('url');
            const body = `Preview is ready: ${url}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          url: ${{ steps.deploy.outputs.url }}

  cleanup-preview:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Install Wrangler CLI
        run: npm i -g wrangler@4
      - name: Delete preview Worker for this PR
        run: |
          NAME="knots-pr-${{ github.event.pull_request.number }}"
          echo "Deleting $NAME"
          yes | wrangler delete --name "$NAME" || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
